#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Hazenet.dk

# Short bio or description (displayed in the header)
description: VMware vSphere, vRealize, Scripting and more

# Author infomation
author: Mads Fog Albrechtslund

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: hazenet
  instagram: 
  linkedin: madsfogalbrechtslund
  pinterest: 
  rss: RSS
  twitter: Hazenet
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: hazenetdk

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-48546849-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://hazenet.dk

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
future: true

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-lunr-js-search
  - jekyll-redirect-from
  - jekyll-paginate
  - rouge

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

host: 0.0.0.0
    
